### PR TITLE
Delete application endpoint

### PR DESCRIPTION
**Pull request by ryan-endacott**
Delete application endpoint. 

Basic doc:

Send a `DELETE` request to `/users/applications/{application_name}`.  You'll receive an updated list of applications back.

### CODE REVIEW

**Comment by ryan-endacott** [comment]
In other news, the travis tests are still flaky, and I have no idea why :(  I suspect it's somehow a rethink on travis issue.  They're never flaky locally, and that's the main difference between vagrant and travis.  Any ideas on finding a fix?  @Felttrip @DrewWeth

**Comment by ryan-endacott** [comment]
Tests passed after a rebuild :confused:

**Comment by Felttrip** [comment]
That sucks, is it the integration tests again? That's what I was having
issues with prior.

**Comment by DrewWeth** [comment]
Code looks good. I would start separating application logic into its own controller though. It's starting to muddle with the user.

**Comment by Felttrip** [comment]
@ryan-endacott in regards to the tests failing maybe we should mock out the db and just assume that it will respond with the proper data.

**Comment by ryan-endacott** [comment]
Hmmm yeah, mocking out the db is probably the ideal solution. Unfortunately
it's a lot of extra work that I'm not sure is worth it.

I don't think we'll have any extra application logic, so do you think it's
worth separating now? Maybe we should separate if/when we add anything
more?

**Comment by Felttrip** [comment]
I agree mocking would take some time to implement. I'll be looking into
potential other fixes.

**Comment by DrewWeth** [comment]
We have to query applications, edit, and probably some other end points. It sounds like applications have their own set of CRUD end points worth separating later

**Comment by ryan-endacott** [comment]
I have an idea of how to test the travis flakiness cause. I'm gonna get a fresh VM and run the exact same install rethinkdb commands that Travis runs and see if the error reproduces.

**Comment by ryan-endacott** [comment]
@Felttrip 

I tried immediately starting a rethinkdb instance with `rethinkdb &` then immediately running the tests with `make`, but they never failed :(

**Pull request merged**
