### PR TITLE
Automated Deployment

### PR DESCRIPTION
**Pull request by Felttrip**
These changes to the travis.yml file allow Travis CI to push to the bare repository which handles the rest of the deployment.

### CODE REVIEW

**Comment by Felttrip** [comment]
@ryan-endacott if you can give this a once over we can get the auto deployments going.

**Comment by ryan-endacott** [comment]
Sorry, I totally missed this PR somehow.  I hereby give it a postmortem LGTM.  Does this all work now?

**Comment by Felttrip** [comment]
Yea this is all good deploys are automated now

**Comment by ryan-endacott** [comment]
Awesome! Thanks Nate!

**Pull request merged**
